// Code generated by goyacc -p calc calc.y. DO NOT EDIT.

//line calc.y:2
package main

import __yyfmt__ "fmt"

//line calc.y:2

import (
	_ "bufio"
	_ "bytes"
	_ "fmt"
	_ "io"
	_ "log"
	_ "math/big"
	_ "os"
	_ "unicode/utf8"
)

//line calc.y:17
type calcSymType struct {
	yys    int
	valI64 *int64
	valF64 *float64
	param  *string
	op     int
}

const LEFT_QUOTE = 57346
const RIGHT_QUOTE = 57347
const LEFT_PAREN = 57348
const RIGHT_PAREN = 57349
const EQ = 57350
const NEQ = 57351
const GT = 57352
const GTE = 57353
const LT = 57354
const LTE = 57355
const AND = 57356
const OR = 57357
const NOT = 57358
const BIT_XOR = 57359
const BIT_AND = 57360
const BIR_OR = 57361
const BIT_NOT = 57362
const LSHIFT = 57363
const RSHIFT = 57364
const PLUS = 57365
const MINUS = 57366
const MULTIPLY = 57367
const DIVIDE = 57368
const MODULUS = 57369
const EXPONENT = 57370
const UNARY_POSITIVE = 57371
const UNARY_NEGATIVE = 57372
const UNARY_NOT = 57373

var calcToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LEFT_QUOTE",
	"RIGHT_QUOTE",
	"LEFT_PAREN",
	"RIGHT_PAREN",
	"EQ",
	"NEQ",
	"GT",
	"GTE",
	"LT",
	"LTE",
	"AND",
	"OR",
	"NOT",
	"BIT_XOR",
	"BIT_AND",
	"BIR_OR",
	"BIT_NOT",
	"LSHIFT",
	"RSHIFT",
	"PLUS",
	"MINUS",
	"MULTIPLY",
	"DIVIDE",
	"MODULUS",
	"EXPONENT",
	"UNARY_POSITIVE",
	"UNARY_NEGATIVE",
	"UNARY_NOT",
}

var calcStatenames = [...]string{}

const calcEofCode = 1
const calcErrCode = 2
const calcInitialStackSize = 16

//line calc.y:82

//line yacctab:1
var calcExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const calcPrivate = 57344

const calcLast = 10

var calcAct = [...]int8{
	4, 6, 7, 4, 2, 1, 3, 0, 0, 5,
}

var calcPact = [...]int16{
	-3, -1000, -1000, -1000, -6, -5, -1000, -1000,
}

var calcPgo = [...]int8{
	0, 4, 6, 5,
}

var calcR1 = [...]int8{
	0, 3, 1, 2, 2,
}

var calcR2 = [...]int8{
	0, 1, 1, 3, 2,
}

var calcChk = [...]int16{
	-1000, -3, -1, -2, 6, -1, 7, 7,
}

var calcDef = [...]int8{
	0, -2, 1, 2, 0, 0, 4, 3,
}

var calcTok1 = [...]int8{
	1,
}

var calcTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
}

var calcTok3 = [...]int8{
	0,
}

var calcErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	calcDebug        = 0
	calcErrorVerbose = false
)

type calcLexer interface {
	Lex(lval *calcSymType) int
	Error(s string)
}

type calcParser interface {
	Parse(calcLexer) int
	Lookahead() int
}

type calcParserImpl struct {
	lval  calcSymType
	stack [calcInitialStackSize]calcSymType
	char  int
}

func (p *calcParserImpl) Lookahead() int {
	return p.char
}

func calcNewParser() calcParser {
	return &calcParserImpl{}
}

const calcFlag = -1000

func calcTokname(c int) string {
	if c >= 1 && c-1 < len(calcToknames) {
		if calcToknames[c-1] != "" {
			return calcToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func calcStatname(s int) string {
	if s >= 0 && s < len(calcStatenames) {
		if calcStatenames[s] != "" {
			return calcStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func calcErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !calcErrorVerbose {
		return "syntax error"
	}

	for _, e := range calcErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + calcTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(calcPact[state])
	for tok := TOKSTART; tok-1 < len(calcToknames); tok++ {
		if n := base + tok; n >= 0 && n < calcLast && int(calcChk[int(calcAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if calcDef[state] == -2 {
		i := 0
		for calcExca[i] != -1 || int(calcExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; calcExca[i] >= 0; i += 2 {
			tok := int(calcExca[i])
			if tok < TOKSTART || calcExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if calcExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += calcTokname(tok)
	}
	return res
}

func calclex1(lex calcLexer, lval *calcSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(calcTok1[0])
		goto out
	}
	if char < len(calcTok1) {
		token = int(calcTok1[char])
		goto out
	}
	if char >= calcPrivate {
		if char < calcPrivate+len(calcTok2) {
			token = int(calcTok2[char-calcPrivate])
			goto out
		}
	}
	for i := 0; i < len(calcTok3); i += 2 {
		token = int(calcTok3[i+0])
		if token == char {
			token = int(calcTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(calcTok2[1]) /* unknown char */
	}
	if calcDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", calcTokname(token), uint(char))
	}
	return char, token
}

func calcParse(calclex calcLexer) int {
	return calcNewParser().Parse(calclex)
}

func (calcrcvr *calcParserImpl) Parse(calclex calcLexer) int {
	var calcn int
	var calcVAL calcSymType
	var calcDollar []calcSymType
	_ = calcDollar // silence set and not used
	calcS := calcrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	calcstate := 0
	calcrcvr.char = -1
	calctoken := -1 // calcrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		calcstate = -1
		calcrcvr.char = -1
		calctoken = -1
	}()
	calcp := -1
	goto calcstack

ret0:
	return 0

ret1:
	return 1

calcstack:
	/* put a state and value onto the stack */
	if calcDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", calcTokname(calctoken), calcStatname(calcstate))
	}

	calcp++
	if calcp >= len(calcS) {
		nyys := make([]calcSymType, len(calcS)*2)
		copy(nyys, calcS)
		calcS = nyys
	}
	calcS[calcp] = calcVAL
	calcS[calcp].yys = calcstate

calcnewstate:
	calcn = int(calcPact[calcstate])
	if calcn <= calcFlag {
		goto calcdefault /* simple state */
	}
	if calcrcvr.char < 0 {
		calcrcvr.char, calctoken = calclex1(calclex, &calcrcvr.lval)
	}
	calcn += calctoken
	if calcn < 0 || calcn >= calcLast {
		goto calcdefault
	}
	calcn = int(calcAct[calcn])
	if int(calcChk[calcn]) == calctoken { /* valid shift */
		calcrcvr.char = -1
		calctoken = -1
		calcVAL = calcrcvr.lval
		calcstate = calcn
		if Errflag > 0 {
			Errflag--
		}
		goto calcstack
	}

calcdefault:
	/* default state action */
	calcn = int(calcDef[calcstate])
	if calcn == -2 {
		if calcrcvr.char < 0 {
			calcrcvr.char, calctoken = calclex1(calclex, &calcrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if calcExca[xi+0] == -1 && int(calcExca[xi+1]) == calcstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			calcn = int(calcExca[xi+0])
			if calcn < 0 || calcn == calctoken {
				break
			}
		}
		calcn = int(calcExca[xi+1])
		if calcn < 0 {
			goto ret0
		}
	}
	if calcn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			calclex.Error(calcErrorMessage(calcstate, calctoken))
			Nerrs++
			if calcDebug >= 1 {
				__yyfmt__.Printf("%s", calcStatname(calcstate))
				__yyfmt__.Printf(" saw %s\n", calcTokname(calctoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for calcp >= 0 {
				calcn = int(calcPact[calcS[calcp].yys]) + calcErrCode
				if calcn >= 0 && calcn < calcLast {
					calcstate = int(calcAct[calcn]) /* simulate a shift of "error" */
					if int(calcChk[calcstate]) == calcErrCode {
						goto calcstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if calcDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", calcS[calcp].yys)
				}
				calcp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if calcDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", calcTokname(calctoken))
			}
			if calctoken == calcEofCode {
				goto ret1
			}
			calcrcvr.char = -1
			calctoken = -1
			goto calcnewstate /* try again in the same state */
		}
	}

	/* reduction by production calcn */
	if calcDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", calcn, calcStatname(calcstate))
	}

	calcnt := calcn
	calcpt := calcp
	_ = calcpt // guard against "declared and not used"

	calcp -= int(calcR2[calcn])
	// calcp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if calcp+1 >= len(calcS) {
		nyys := make([]calcSymType, len(calcS)*2)
		copy(nyys, calcS)
		calcS = nyys
	}
	calcVAL = calcS[calcp+1]

	/* consult goto table to find next state */
	calcn = int(calcR1[calcn])
	calcg := int(calcPgo[calcn])
	calcj := calcg + calcS[calcp].yys + 1

	if calcj >= calcLast {
		calcstate = int(calcAct[calcg])
	} else {
		calcstate = int(calcAct[calcj])
		if int(calcChk[calcstate]) != -calcn {
			calcstate = int(calcAct[calcg])
		}
	}
	// dummy call; replaced with literal code
	switch calcnt {

	case 1:
		calcDollar = calcS[calcpt-1 : calcpt+1]
//line calc.y:62
		{
			//setScannerData(yylex, $1)
		}
	case 2:
		calcDollar = calcS[calcpt-1 : calcpt+1]
//line calc.y:68
		{
			calcVAL.expr = calcDollar[1].expr
		}
	case 3:
		calcDollar = calcS[calcpt-3 : calcpt+1]
//line calc.y:74
		{
			calcVAL.expr = calcDollar[2].expr
		}
	case 4:
		calcDollar = calcS[calcpt-2 : calcpt+1]
//line calc.y:78
		{

		}
	}
	goto calcstack /* stack new state and value */
}
